src/Entity/Chef.php
<?php

namespace App\Entity;

use App\Repository\ChefRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: ChefRepository::class)]
class Chef implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
         if ($this->getUser()) {
             return $this->redirectToRoute('sonata_admin_dashboard');
         }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logoutv')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/login.html.twig
{#<form method="post">#}
{#    {% if error %}#}
{#        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>#}
{#    {% endif %}#}

{#    {% if app.user %}#}
{#        <div class="mb-3">#}
{#            You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logoutv') }}">Logout</a>#}
{#        </div>#}
{#    {% endif %}#}

{#    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>#}
{#    <label for="inputEmail">Email</label>#}
{#    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>#}
{#    <label for="inputPassword">Password</label>#}
{#    <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>#}

{#    <input type="hidden" name="_csrf_token"#}
{#           value="{{ csrf_token('authenticate') }}"#}
{#    >#}


{#        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.#}
{#        See https://symfony.com/doc/current/security/remember_me.html#}

{#        <div class="checkbox mb-3">#}
{#            <label>#}
{#                <input type="checkbox" name="_remember_me"> Remember me#}
{#            </label>#}
{#        </div>#}


{#    <button class="btn btn-lg btn-primary" type="submit">#}
{#        Sign in#}
{#    </button>#}
{#</form>#}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Identifiant</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
    <style>


        body{background: #ECF0F5}.card{border: none;height: 320px}.forms-inputs{position: relative}.forms-inputs span{position: absolute;top:-18px;left: 10px;background-color: #fff;padding: 5px 10px;font-size: 15px}.forms-inputs input{height: 50px;width: 100%;border: 2px solid #eee}.forms-inputs input:focus{box-shadow: none;outline: none;border: 2px solid #000}.btn{height: 50px}.success-data{display: flex;flex-direction: column}.bxs-badge-check{font-size: 90px}
    </style>
</head>

<body>
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div class="card px-5 py-5" id="form1" style="height: 575px;">
                <div class="text-center mb-4">
                    <img  style="width: 95px;" src="{{ asset('/img/Groupe.png') }}" alt="Logo" class=" mb-4">
                    <h5>Bienvenue dans la plateforme de relève des compteurs "BT/BP"</h5>
                    <p style="color: #222D32;opacity: 1;">Merci de mettre votre nom et votre mot de passe …</p>
                </div>
                <div class="form-data" >
                    <form method="post">
                    <div class="forms-inputs mb-4">
                        <span>Email or username</span>
                        <input name="email" id="inputEmail" autocomplete="off" type="text" >
                        <div class="invalid-feedback">A valid email is required!</div>
                    </div>

                    <div class="forms-inputs mb-4">
                        <span>Password</span>
                        <input name="password" id="inputPassword" autocomplete="off" type="password">
                        <div class="invalid-feedback">Password must be 8 characters long!</div>
                    </div>

                    <div class="mb-3">
                        <input type="hidden" name="_csrf_token"
                               value="{{ csrf_token('authenticate') }}"
                        >
                        <button style="background-color: #005FAE" type="submit" class="btn btn-primary w-100">S'IDENTIFIER</button>
                    </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

<!-- Bootstrap JS -->

</body>

</html>